import SummaryCard from "../SummaryCard";
import SectionHeading from "../SectionHeading";
import Empty from "../Empty";
import BookingCard from "../BookingsDetails/BookingCard";
import { dateText, getDate, statusClass } from "../../../utils/dashboardUtils";

function Home(
    { 
        firstName, events, bookings, upcoming, pending, approved, unread, onFind, onBooking, onNotifications }) { return <><section className="compact-welcome"><div><p className="welcome-eyebrow">YOUR BOOKING SPACE</p><h2>Good morning, {firstName}</h2><p>{events.length} {events.length === 1 ? "event" : "events"} in your workspace.</p></div><button className="primary-action" onClick={onFind}>⌖ Find a Venue</button></section><section className="summary-grid compact-summary"><SummaryCard icon="◷" label="Upcoming" value={upcoming.length} tone="blue" /><SummaryCard icon="…" label="Pending" value={pending} tone="yellow" /><SummaryCard icon="✓" label="Approved" value={approved} tone="green" /></section><section className="dashboard-grid compact-grid"><div className="dashboard-column"><SectionHeading kicker="YOUR SCHEDULE" title="Upcoming bookings" action="View bookings" onClick={() => document.querySelector(".menu-button")?.click()} />{upcoming.length ? <div className="booking-list">{upcoming.slice(0, 2).map((booking) => <BookingCard key={booking.bookingId} booking={booking} onOpen={onBooking} />)}</div> : <Empty title="No bookings yet" text="Find a venue and create your first booking." action="Find a Venue" onAction={onFind} />}<SectionHeading kicker="RECENT ACTIVITY" title="Booking activity" action="Notifications" onClick={onNotifications} /><div className="activity-list">{bookings.slice(0, 4).map((booking) => <div className="activity-item" key={booking.bookingId}><span className={`activity-icon ${statusClass(booking.statusName)}`}>{booking.statusName === "Approved" ? "✓" : booking.statusName === "Rejected" ? "!" : "•"}</span><div><strong>{booking.statusName || "Pending"} booking</strong><p>{booking.eventName || "Event booking"}</p></div><time>{dateText(getDate(booking))}</time></div>)}</div></div><aside className="dashboard-rail compact-rail"><div className="updates-panel"><SectionHeading kicker="STAY IN THE LOOP" title="Notifications" action="Open" onClick={onNotifications} /><div className="update-summary"><strong>{unread ? `${unread} unread update${unread === 1 ? "" : "s"}` : "You're all caught up"}</strong><p>Important booking updates will appear here.</p></div></div><div className="venue-prompt compact-prompt"><div className="venue-prompt-content"><p className="section-kicker">READY TO PLAN?</p><h3>Find a space for your next event.</h3><button onClick={onFind}>Explore venues <span>→</span></button></div></div></aside></section></>; 
    }

export default Home;
